[2024-03-23T11:33:38.194+0000] {processor.py:161} INFO - Started process (PID=45964) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:33:38.195+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:33:38.196+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:33:38.195+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:33:38.198+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:33:38.197+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 33
    read_data=
             ^
SyntaxError: invalid syntax
[2024-03-23T11:33:38.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:33:38.221+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.030 seconds
[2024-03-23T11:33:48.133+0000] {processor.py:161} INFO - Started process (PID=46114) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:33:48.133+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:33:48.135+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:33:48.134+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:33:48.137+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:33:48.137+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 13
    data =
          ^
SyntaxError: invalid syntax
[2024-03-23T11:33:48.138+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:33:48.161+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.032 seconds
[2024-03-23T11:33:51.353+0000] {processor.py:161} INFO - Started process (PID=46131) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:33:51.354+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:33:51.354+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:33:51.354+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:33:51.357+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:33:51.356+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 34
    read_data=
             ^
SyntaxError: invalid syntax
[2024-03-23T11:33:51.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:33:51.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.032 seconds
[2024-03-23T11:33:54.420+0000] {processor.py:161} INFO - Started process (PID=46141) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:33:54.421+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:33:54.422+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:33:54.422+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:33:54.424+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:33:54.424+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 34
    read_data=
             ^
SyntaxError: invalid syntax
[2024-03-23T11:33:54.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:33:54.446+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.029 seconds
[2024-03-23T11:33:56.903+0000] {processor.py:161} INFO - Started process (PID=46152) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:33:56.903+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:33:56.904+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:33:56.904+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:33:56.907+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:33:56.906+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 34
    read_data=
             ^
SyntaxError: invalid syntax
[2024-03-23T11:33:56.907+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:33:56.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.029 seconds
[2024-03-23T11:34:12.801+0000] {processor.py:161} INFO - Started process (PID=46283) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:12.802+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:34:12.803+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:12.803+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:12.806+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:12.805+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 34
    upload_gcs=
              ^
SyntaxError: invalid syntax
[2024-03-23T11:34:12.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:12.832+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.036 seconds
[2024-03-23T11:34:15.108+0000] {processor.py:161} INFO - Started process (PID=46313) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:15.110+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:34:15.116+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:15.116+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:15.120+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:15.119+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 34
    upload_gcs =
               ^
SyntaxError: invalid syntax
[2024-03-23T11:34:15.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:15.154+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.050 seconds
[2024-03-23T11:34:17.024+0000] {processor.py:161} INFO - Started process (PID=46368) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:17.025+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:34:17.026+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:17.026+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:17.029+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:17.028+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 34
    upload_gcs =
                ^
SyntaxError: invalid syntax
[2024-03-23T11:34:17.030+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:17.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.041 seconds
[2024-03-23T11:34:18.546+0000] {processor.py:161} INFO - Started process (PID=46401) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:18.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:34:18.548+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:18.548+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:18.551+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:18.550+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 34
    upload_gcs =
                ^
SyntaxError: invalid syntax
[2024-03-23T11:34:18.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:18.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.032 seconds
[2024-03-23T11:34:21.678+0000] {processor.py:161} INFO - Started process (PID=46423) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:21.679+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:34:21.680+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:21.679+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:21.684+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:21.683+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 34, in <module>
    upload_gcs = LocalF
NameError: name 'LocalF' is not defined
[2024-03-23T11:34:21.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:21.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.029 seconds
[2024-03-23T11:34:22.739+0000] {processor.py:161} INFO - Started process (PID=46431) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:22.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:34:22.741+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:22.741+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:22.749+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:22.748+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 34, in <module>
    upload_gcs = LocalFiles
NameError: name 'LocalFiles' is not defined
[2024-03-23T11:34:22.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:22.772+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.036 seconds
[2024-03-23T11:34:26.791+0000] {processor.py:161} INFO - Started process (PID=46438) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:26.792+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:34:26.793+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:26.793+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:26.801+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:26.800+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 34, in <module>
    upload_gcs = LocalFilesystem
NameError: name 'LocalFilesystem' is not defined
[2024-03-23T11:34:26.801+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:26.822+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.033 seconds
[2024-03-23T11:34:30.395+0000] {processor.py:161} INFO - Started process (PID=46459) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:30.396+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:34:30.397+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:30.397+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:30.402+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:30.402+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 34, in <module>
    upload_gcs = LocalFilesystemToGCS
NameError: name 'LocalFilesystemToGCS' is not defined
[2024-03-23T11:34:30.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:30.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.042 seconds
[2024-03-23T11:34:36.277+0000] {processor.py:161} INFO - Started process (PID=46534) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:36.278+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:34:36.278+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:36.278+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:36.283+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:36.283+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 34, in <module>
    upload_gcs = LocalFilesystemToGCSOpearator
NameError: name 'LocalFilesystemToGCSOpearator' is not defined
[2024-03-23T11:34:36.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:36.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.029 seconds
[2024-03-23T11:34:40.573+0000] {processor.py:161} INFO - Started process (PID=46555) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:40.574+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:34:40.575+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:40.574+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:40.581+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:40.580+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 34, in <module>
    upload_gcs = LocalFilesystemToGCSOpearator(
NameError: name 'LocalFilesystemToGCSOpearator' is not defined
[2024-03-23T11:34:40.582+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:40.606+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.037 seconds
[2024-03-23T11:34:47.921+0000] {processor.py:161} INFO - Started process (PID=46665) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:47.922+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:34:47.923+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:47.923+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:47.931+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:47.929+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 34, in <module>
    upload_gcs = LocalFilesystemToGCSOpearator(
NameError: name 'LocalFilesystemToGCSOpearator' is not defined
[2024-03-23T11:34:47.931+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:47.956+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.038 seconds
[2024-03-23T11:34:53.656+0000] {processor.py:161} INFO - Started process (PID=46715) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:53.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:34:53.664+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:53.664+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:53.680+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:34:53.677+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:34:53.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:34:53.765+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.117 seconds
[2024-03-23T11:35:24.394+0000] {processor.py:161} INFO - Started process (PID=46977) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:35:24.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:35:24.396+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:35:24.396+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:35:24.408+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:35:24.401+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:35:24.408+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:35:24.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.043 seconds
[2024-03-23T11:35:54.761+0000] {processor.py:161} INFO - Started process (PID=47239) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:35:54.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:35:54.763+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:35:54.763+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:35:54.769+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:35:54.768+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:35:54.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:35:54.796+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.039 seconds
[2024-03-23T11:36:25.245+0000] {processor.py:161} INFO - Started process (PID=47501) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:36:25.246+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:36:25.247+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:36:25.247+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:36:25.253+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:36:25.252+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:36:25.254+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:36:25.279+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.036 seconds
[2024-03-23T11:36:55.492+0000] {processor.py:161} INFO - Started process (PID=47763) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:36:55.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:36:55.494+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:36:55.494+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:36:55.500+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:36:55.499+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:36:55.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:36:55.527+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.038 seconds
[2024-03-23T11:37:25.617+0000] {processor.py:161} INFO - Started process (PID=48025) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:37:25.618+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:37:25.619+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:37:25.619+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:37:25.625+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:37:25.624+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:37:25.626+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:37:25.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.039 seconds
[2024-03-23T11:37:56.192+0000] {processor.py:161} INFO - Started process (PID=48288) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:37:56.192+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:37:56.193+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:37:56.193+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:37:56.199+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:37:56.198+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:37:56.200+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:37:56.224+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.036 seconds
[2024-03-23T11:38:26.503+0000] {processor.py:161} INFO - Started process (PID=48550) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:38:26.504+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:38:26.506+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:38:26.506+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:38:26.513+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:38:26.511+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:38:26.513+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:38:26.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.042 seconds
[2024-03-23T11:38:57.051+0000] {processor.py:161} INFO - Started process (PID=48812) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:38:57.052+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:38:57.053+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:38:57.052+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:38:57.058+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:38:57.057+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:38:57.059+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:38:57.083+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.036 seconds
[2024-03-23T11:39:27.646+0000] {processor.py:161} INFO - Started process (PID=49075) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:39:27.646+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:39:27.647+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:39:27.647+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:39:27.653+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:39:27.652+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:39:27.653+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:39:27.678+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.036 seconds
[2024-03-23T11:39:57.741+0000] {processor.py:161} INFO - Started process (PID=49336) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:39:57.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:39:57.743+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:39:57.743+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:39:57.749+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:39:57.748+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:39:57.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:39:57.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.038 seconds
[2024-03-23T11:40:28.238+0000] {processor.py:161} INFO - Started process (PID=49595) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:40:28.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:40:28.240+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:40:28.239+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:40:28.246+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:40:28.244+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:40:28.246+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:40:28.276+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.042 seconds
[2024-03-23T11:40:58.753+0000] {processor.py:161} INFO - Started process (PID=49857) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:40:58.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:40:58.755+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:40:58.754+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:40:58.760+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:40:58.759+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:40:58.761+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:40:58.791+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.041 seconds
[2024-03-23T11:41:29.537+0000] {processor.py:161} INFO - Started process (PID=50119) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:41:29.539+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:41:29.540+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:41:29.539+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:41:29.546+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:41:29.545+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:41:29.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:41:29.574+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.040 seconds
[2024-03-23T11:41:59.717+0000] {processor.py:161} INFO - Started process (PID=50381) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:41:59.723+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:41:59.724+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:41:59.724+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:41:59.731+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:41:59.730+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:41:59.731+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:41:59.764+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.052 seconds
[2024-03-23T11:42:30.058+0000] {processor.py:161} INFO - Started process (PID=50645) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:42:30.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:42:30.060+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:42:30.060+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:42:30.065+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:42:30.064+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:42:30.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:42:30.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.034 seconds
[2024-03-23T11:43:00.244+0000] {processor.py:161} INFO - Started process (PID=50907) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:43:00.247+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:43:00.248+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:43:00.247+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:43:00.254+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:43:00.254+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:43:00.258+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:43:00.285+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.045 seconds
[2024-03-23T11:43:30.428+0000] {processor.py:161} INFO - Started process (PID=51169) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:43:30.429+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:43:30.430+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:43:30.430+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:43:30.443+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:43:30.442+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:43:30.443+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:43:30.468+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.043 seconds
[2024-03-23T11:44:00.619+0000] {processor.py:161} INFO - Started process (PID=51432) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:44:00.620+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:44:00.621+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:44:00.620+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:44:00.626+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:44:00.626+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:44:00.627+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:44:00.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.038 seconds
[2024-03-23T11:44:30.977+0000] {processor.py:161} INFO - Started process (PID=51694) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:44:30.978+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:44:30.979+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:44:30.979+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:44:30.985+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:44:30.984+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 37, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:44:30.986+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:44:31.012+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.038 seconds
[2024-03-23T11:44:51.623+0000] {processor.py:161} INFO - Started process (PID=51831) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:44:51.624+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:44:51.624+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:44:51.624+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:44:51.629+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:44:51.629+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 38, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:44:51.630+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:44:51.651+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.031 seconds
[2024-03-23T11:45:11.951+0000] {processor.py:161} INFO - Started process (PID=52012) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:45:11.952+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:45:11.953+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:45:11.952+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:45:11.958+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:45:11.958+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 38, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:45:11.959+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:45:11.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.042 seconds
[2024-03-23T11:45:17.723+0000] {processor.py:161} INFO - Started process (PID=52072) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:45:17.724+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:45:17.725+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:45:17.725+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:45:17.732+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:45:17.731+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 38, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:45:17.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:45:17.758+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.038 seconds
[2024-03-23T11:45:19.120+0000] {processor.py:161} INFO - Started process (PID=52083) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:45:19.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:45:19.122+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:45:19.121+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:45:19.126+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:45:19.125+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 38, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:45:19.126+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:45:19.148+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.031 seconds
[2024-03-23T11:45:21.278+0000] {processor.py:161} INFO - Started process (PID=52098) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:45:21.280+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:45:21.281+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:45:21.280+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:45:21.288+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:45:21.287+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 39, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-03-23T11:45:21.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:45:21.314+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.039 seconds
[2024-03-23T11:45:29.494+0000] {processor.py:161} INFO - Started process (PID=52188) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:45:29.496+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:45:29.497+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:45:29.496+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:45:29.500+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:45:29.500+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with
        ^
SyntaxError: invalid syntax
[2024-03-23T11:45:29.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:45:29.530+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.039 seconds
[2024-03-23T11:45:32.207+0000] {processor.py:161} INFO - Started process (PID=52243) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:45:32.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:45:32.209+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:45:32.209+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:45:32.212+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:45:32.211+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open
            ^
SyntaxError: invalid syntax
[2024-03-23T11:45:32.213+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:45:32.240+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.036 seconds
[2024-03-23T11:46:02.516+0000] {processor.py:161} INFO - Started process (PID=52505) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:46:02.517+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:46:02.518+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:46:02.518+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:46:02.521+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:46:02.520+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open
            ^
SyntaxError: invalid syntax
[2024-03-23T11:46:02.521+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:46:02.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.034 seconds
[2024-03-23T11:46:32.874+0000] {processor.py:161} INFO - Started process (PID=52768) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:46:32.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:46:32.876+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:46:32.875+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:46:32.878+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:46:32.878+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open
            ^
SyntaxError: invalid syntax
[2024-03-23T11:46:32.879+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:46:32.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.035 seconds
[2024-03-23T11:47:03.334+0000] {processor.py:161} INFO - Started process (PID=53030) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:47:03.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:47:03.336+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:47:03.335+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:47:03.339+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:47:03.338+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open
            ^
SyntaxError: invalid syntax
[2024-03-23T11:47:03.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:47:03.371+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.040 seconds
[2024-03-23T11:47:33.824+0000] {processor.py:161} INFO - Started process (PID=53292) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:47:33.825+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:47:33.827+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:47:33.826+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:47:33.830+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:47:33.829+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open
            ^
SyntaxError: invalid syntax
[2024-03-23T11:47:33.830+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:47:33.857+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.036 seconds
[2024-03-23T11:48:04.699+0000] {processor.py:161} INFO - Started process (PID=53554) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:48:04.700+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:48:04.702+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:48:04.701+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:48:04.705+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:48:04.704+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open
            ^
SyntaxError: invalid syntax
[2024-03-23T11:48:04.705+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:48:04.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.034 seconds
[2024-03-23T11:48:35.271+0000] {processor.py:161} INFO - Started process (PID=53816) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:48:35.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:48:35.273+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:48:35.273+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:48:35.276+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:48:35.275+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open
            ^
SyntaxError: invalid syntax
[2024-03-23T11:48:35.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:48:35.300+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.033 seconds
[2024-03-23T11:49:05.620+0000] {processor.py:161} INFO - Started process (PID=54079) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:49:05.621+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:49:05.622+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:49:05.621+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:49:05.624+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:49:05.624+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open
            ^
SyntaxError: invalid syntax
[2024-03-23T11:49:05.625+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:49:05.655+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.039 seconds
[2024-03-23T11:49:35.814+0000] {processor.py:161} INFO - Started process (PID=54341) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:49:35.815+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:49:35.817+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:49:35.816+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:49:35.821+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:49:35.820+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open
            ^
SyntaxError: invalid syntax
[2024-03-23T11:49:35.822+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:49:35.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.038 seconds
[2024-03-23T11:49:46.738+0000] {processor.py:161} INFO - Started process (PID=54405) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:49:46.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:49:46.740+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:49:46.740+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:49:46.743+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:49:46.781+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.046 seconds
[2024-03-23T11:50:17.071+0000] {processor.py:161} INFO - Started process (PID=54659) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:50:17.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-03-23T11:50:17.073+0000] {logging_mixin.py:188} INFO - [2024-03-23T11:50:17.072+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:50:17.075+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-03-23T11:50:17.090+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.023 seconds
